# Generated by Django 3.2 on 2022-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('unired_id', models.IntegerField(blank=True, null=True)),
                ('last_otp_token', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number_is_contact', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('is_registered', models.BooleanField(blank=True, default=False, null=True)),
                ('password', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
